### ISSUE TITLE
Document Wire Protocol

### ISSUE THREAD

**Issue by wanderer** [dominictarr/epidemic-broadcast-trees#7]
It would be nice to have a Documentation on the Wire Protocol. Doing some simple debugging I see that the vector clock is first exchanged then the sequences are sent. But how is backpressure handled?

**Comment by dominictarr** [comment]
vector clocks can actually be sent at any time (since they are also used to switch peers into sending or not sending mode)

back pressure comes from the stream, i.e. tcp, although in ssb it currently uses muxrpc which does not have backpressure yet (TODO!)

If you want to use ebt standalone, i'd recommend just passing the raw stream through a serializer,

``` js
var stream = createEBTStream() //ebt stream
return {
  source: pull(stream.source, encodeStream) sink: pull(decodeStream, stream.sink)
}
```
or, a simple solution is https://www.npmjs.com/package/pull-json-doubleline

``` js
var pullJSON = require('pull-json-doubleline')
return pullJSON(createEBTStream())
```
but it would also be fairly simple to use a binary encoding

**Comment by wanderer** [comment]
thanks!
